export default {
  GET_MOVIE_LIST: "GET_MOVIE_LIST",
  GET_MOVIE_LIST_COMPLETED: "GET_MOVIE_LIST_COMPLETED",
  GET_MOVIE_LIST_ERROR: "GET_MOVIE_LIST_ERROR",
  REMOVE_MOVIE_FROM_LIST: "REMOVE_MOVIE_FROM_LIST",
};
